# Generated by Django 4.2.2 on 2023-07-13 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matriculasLabs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='docente',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.CreateModel(
            name='Delegado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matriculasLabs.asignatura')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matriculasLabs.estudiante')),
            ],
        ),
    ]
