# Generated by Django 4.2.2 on 2023-07-13 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matriculasLabs', '0002_estudiante_alter_asignatura_name_alter_docente_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='delegado',
            unique_together={('estudiante', 'asignatura')},
        ),
    ]
